name: gesundheit
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.5
  hooks_riverpod: 2.0.2
  fhir: ^0.9.1
  fhir_at_rest: ^0.9.1
  fhir_auth: ^0.9.0-2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_login: ^4.0.0
  freezed_annotation: ^2.2.0
  gap: ^2.0.0
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  go_router: ^5.1.0
  intl: ^0.17.0
  json_annotation: ^4.7.0
  mdi: ^5.0.0-nullsafety.0
  package_info_plus: ^2.0.0
  shared_preferences: ^2.0.15

dev_dependencies:
  build_runner: ^2.3.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.2.0
  go_router_builder: ^1.0.14
  json_serializable: ^6.5.1

flutter:
  uses-material-design: true
  generate: true
  